// <auto-generated />
using System;
using TizianaTerenzi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace TizianaTerenzi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200917195301_Add_Initial_Data_Models")]
    partial class Add_Initial_Data_Models
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TizianaTerenzi.Data.Models.ApplicationRole", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DeletedOn")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<DateTime?>("ModifiedOn")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(256)")
                    .HasMaxLength(256);

                b.Property<string>("NormalizedName")
                    .HasColumnType("nvarchar(256)")
                    .HasMaxLength(256);

                b.HasKey("Id");

                b.HasIndex("IsDeleted");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasName("RoleNameIndex")
                    .HasFilter("[NormalizedName] IS NOT NULL");

                b.ToTable("AspNetRoles");
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.ApplicationUser", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("int");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DeletedOn")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .HasColumnType("nvarchar(256)")
                    .HasMaxLength(256);

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("bit");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(30)")
                    .HasMaxLength(30);

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("nvarchar(30)")
                    .HasMaxLength(30);

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("bit");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("datetimeoffset");

                b.Property<DateTime?>("ModifiedOn")
                    .HasColumnType("datetime2");

                b.Property<string>("NormalizedEmail")
                    .HasColumnType("nvarchar(256)")
                    .HasMaxLength(256);

                b.Property<string>("NormalizedUserName")
                    .HasColumnType("nvarchar(256)")
                    .HasMaxLength(256);

                b.Property<string>("PasswordHash")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("bit");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("bit");

                b.Property<string>("UserName")
                    .HasColumnType("nvarchar(256)")
                    .HasMaxLength(256);

                b.HasKey("Id");

                b.HasIndex("IsDeleted");

                b.HasIndex("NormalizedEmail")
                    .HasName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasName("UserNameIndex")
                    .HasFilter("[NormalizedUserName] IS NOT NULL");

                b.ToTable("AspNetUsers");
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.DiscountCode", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DeletedOn")
                    .HasColumnType("datetime2");

                b.Property<double>("Discount")
                    .HasColumnType("float");

                b.Property<DateTime?>("ExpiresOn")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<DateTime?>("ModifiedOn")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("IsDeleted");

                b.ToTable("DiscountCodes");
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.FragranceGroup", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DeletedOn")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<DateTime?>("ModifiedOn")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("IsDeleted");

                b.ToTable("FragranceGroups");
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.Note", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DeletedOn")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<DateTime?>("ModifiedOn")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("IsDeleted");

                b.ToTable("Notes");
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.Order", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DeletedOn")
                    .HasColumnType("datetime2");

                b.Property<int?>("DiscountCodeId")
                    .HasColumnType("int");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<DateTime?>("ModifiedOn")
                    .HasColumnType("datetime2");

                b.Property<int>("StatusId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("IsDeleted");

                b.HasIndex("UserId");

                b.HasIndex("StatusId");

                b.ToTable("Orders");
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.OrderProduct", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DeletedOn")
                    .HasColumnType("datetime2");

                b.Property<int?>("DiscountCodeId")
                   .HasColumnType("int");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<DateTime?>("ModifiedOn")
                    .HasColumnType("datetime2");

                b.Property<int?>("OrderId")
                    .HasColumnType("int");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("ProductId")
                    .HasColumnType("int");

                b.Property<int>("Quantity")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("IsDeleted");

                b.HasIndex("OrderId");

                b.HasIndex("ProductId");

                b.ToTable("OrderProducts");
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.OrderStatus", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DeletedOn")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<DateTime?>("ModifiedOn")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("IsDeleted");

                b.ToTable("OrderStatuses");
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.Product", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DeletedOn")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("FragranceGroupId")
                    .HasColumnType("int");

                b.Property<string>("Picture")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<DateTime?>("ModifiedOn")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("ProductTypeId")
                    .HasColumnType("int");

                b.Property<int>("YearOfManufacture")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("FragranceGroupId");

                b.HasIndex("IsDeleted");

                b.HasIndex("ProductTypeId");

                b.ToTable("Products");
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.ProductInTheCart", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DeletedOn")
                    .HasColumnType("datetime2");

                b.Property<int?>("DiscountCodeId")
                    .HasColumnType("int");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<DateTime?>("ModifiedOn")
                    .HasColumnType("datetime2");

                b.Property<int>("ProductId")
                    .HasColumnType("int");

                b.Property<int>("Quantity")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("IsDeleted");

                b.HasIndex("UserId");

                b.HasIndex("ProductId");

                b.ToTable("ProductsInTheCart");
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.ProductNotes", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DeletedOn")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<DateTime?>("ModifiedOn")
                    .HasColumnType("datetime2");

                b.Property<int>("NoteId")
                    .HasColumnType("int");

                b.Property<int>("ProductId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("IsDeleted");

                b.HasIndex("NoteId");

                b.HasIndex("ProductId");

                b.ToTable("ProductNotes");
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.ProductType", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DeletedOn")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<DateTime?>("ModifiedOn")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("IsDeleted");

                b.ToTable("ProductTypes");
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.Review", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DeletedOn")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<DateTime?>("ModifiedOn")
                    .HasColumnType("datetime2");

                b.Property<int>("ProductId")
                    .HasColumnType("int");

                b.Property<string>("ReviewText")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("IsDeleted");

                b.HasIndex("UserId");

                b.HasIndex("ProductId");

                b.ToTable("Reviews");
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.Setting", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DeletedOn")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<DateTime?>("ModifiedOn")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Value")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("IsDeleted");

                b.ToTable("Settings");
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.Subscriber", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DeletedOn")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<DateTime?>("ModifiedOn")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("IsDeleted");

                b.ToTable("Subscribers");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("ClaimType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ClaimValue")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RoleId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("AspNetRoleClaims");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("ClaimType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ClaimValue")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserClaims");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ProviderKey")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ProviderDisplayName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("LoginProvider", "ProviderKey");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserLogins");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("RoleId")
                    .HasColumnType("nvarchar(450)");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("AspNetUserRoles");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("LoginProvider")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Value")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("UserId", "LoginProvider", "Name");

                b.ToTable("AspNetUserTokens");
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.Order", b =>
            {
                b.HasOne("TizianaTerenzi.Data.Models.ApplicationUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId");

                b.HasOne("TizianaTerenzi.Data.Models.OrderStatus", "Status")
                    .WithMany()
                    .HasForeignKey("StatusId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.OrderProduct", b =>
            {
                b.HasOne("TizianaTerenzi.Data.Models.Order", null)
                    .WithMany("Products")
                    .HasForeignKey("OrderId");

                b.HasOne("TizianaTerenzi.Data.Models.Product", "Product")
                    .WithMany()
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.Product", b =>
            {
                b.HasOne("TizianaTerenzi.Data.Models.FragranceGroup", "FragranceGroup")
                    .WithMany("Products")
                    .HasForeignKey("FragranceGroupId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("TizianaTerenzi.Data.Models.ProductType", "ProductType")
                    .WithMany("Products")
                    .HasForeignKey("ProductTypeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.ProductInTheCart", b =>
            {
                b.HasOne("TizianaTerenzi.Data.Models.ApplicationUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId");

                b.HasOne("TizianaTerenzi.Data.Models.Product", "Product")
                    .WithMany()
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.ProductNotes", b =>
            {
                b.HasOne("TizianaTerenzi.Data.Models.Note", "Note")
                    .WithMany("Products")
                    .HasForeignKey("NoteId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("TizianaTerenzi.Data.Models.Product", "Product")
                    .WithMany("Notes")
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("TizianaTerenzi.Data.Models.Review", b =>
            {
                b.HasOne("TizianaTerenzi.Data.Models.ApplicationUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId");

                b.HasOne("TizianaTerenzi.Data.Models.Product", "Product")
                    .WithMany("Reviews")
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.HasOne("TizianaTerenzi.Data.Models.ApplicationRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.HasOne("TizianaTerenzi.Data.Models.ApplicationUser", null)
                    .WithMany("Claims")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.HasOne("TizianaTerenzi.Data.Models.ApplicationUser", null)
                    .WithMany("Logins")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.HasOne("TizianaTerenzi.Data.Models.ApplicationRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("TizianaTerenzi.Data.Models.ApplicationUser", null)
                    .WithMany("Roles")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.HasOne("TizianaTerenzi.Data.Models.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}