apiVersion: v1
kind: PersistentVolumeClaim ## We define a PersistentVolumeClaim to provide persistent storage for the administration service, which is necessary for storing data such as data protection keys that need to persist across pod restarts and can be shared with any related cron jobs.
metadata:
  name: administration-service-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---
apiVersion: v1
kind: Service
metadata:
  name: administration-service
spec:
  type: LoadBalancer ## We use a LoadBalancer service type for our administration service to expose it externally and allow other services and clients to access it. The LoadBalancer will automatically provision an external IP address and route traffic to the service, making it accessible from outside the Kubernetes cluster.
  ports:
    - port: 5017
      targetPort: 8080
  selector:
    web-service: administration ## The selector is used to identify the pods that belong to this service. It matches the labels defined in the pod template of the administration service Deployment.

---
## Install Metrics Server for HPA to work url from GitHub
## kubectl edit deployment metrics-server -n kube-system
## Add the following args to the container spec (be careful for tabs in front of the args):
# containers:
# - name: metrics-server
#   args:
#   - --kubelet-insecure-tls
#   - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: administration-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: administration-service ## The name of the Deployment to scale, which should match the name of the administration service Deployment defined later in this file.
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  administration-service
spec:
  replicas: 2 ## We start with 2 replicas for the administration service to ensure high availability and load balancing from the beginning. This allows us to handle more traffic and provides redundancy in case one of the pods goes down, which is important for a critical service like the administration service.
  selector:
    matchLabels:
      web-service: administration ## The selector is used to identify the pods that belong to this Deployment. It matches the labels defined in the pod template below.
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 ## We use a rolling update strategy with maxUnavailable: 1 and maxSurge: 1 to ensure that there is always at least one instance of the administration service running during updates, which helps maintain availability and minimize downtime for this critical service.
  template:
    metadata:
      labels:
        web-service: administration ## The label “web-service: administration” is used to identify the pods that belong to this Deployment and to match the selector defined above. It also helps us filter our administration service pods later using kubectl commands (e.g., kubectl get pods -l web-service=administration).
        system: server ## The “system” label is here to help us filter our server pods later: kubectl get pods -l system=server
    spec:
      terminationGracePeriodSeconds: 20 ## We set a termination grace period of 20 seconds to allow the administration service to shut down gracefully and complete any ongoing requests before the pod is terminated, which helps prevent data loss and ensures a better user experience.
      containers:
      - name:  administration-service ## The name of the container, which will be used in logs and for referencing the container.
        image:  borislechev/tizianaterenzimicroservices-administration-service:1.0.23 ## The Docker image for the administration service, which should be built and pushed to a container registry before deploying to Kubernetes. The image name can include a tag (e.g., administration-service:1.0) if needed.
        imagePullPolicy: IfNotPresent ## The image pull policy is set to “IfNotPresent” to prevent unnecessary downloads and speed up deployments by using cached images when available.
        ports:
        - containerPort: 8080 ## The port on which the administration service container listens for incoming HTTP requests. This should match the port configuration in the application itself.
        resources:
          requests:
            cpu: "250m" ## The amount of CPU resources requested for the container. This helps Kubernetes schedule the pod on a node that has enough resources to run it.
            memory: "256Mi" ## The amount of memory resources requested for the container. This helps Kubernetes schedule the pod on a node that has enough resources to run it.
          limits:
            cpu: "500m" ## The maximum amount of CPU resources requested for the container. This helps Kubernetes schedule the pod on a node that has enough resources to run it.
            memory: "512Mi" ## The maximum amount of memory resources requested for the container. This helps Kubernetes schedule the pod on a node that has enough resources to run it.
        env:
        - name:  ApplicationSettings__Secret
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-secret ## The security token secret is stored in the environment-secrets Kubernetes Secret and is injected into the container as an environment variable. This allows the administration service to access the secret value securely without hardcoding it in the application code or configuration files.
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: administration-service-connection-string ## The connection string for the administration database is stored in the environment-secrets Kubernetes Secret and is injected into the container as an environment variable. This allows the administration service to connect to the database securely without hardcoding the connection string in the application code or configuration files.
        - name: ConnectionStrings__CronJobsConnection
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: administration-service-cron-jobs-connection-string ## The connection string for the administration database used by cron jobs is stored in the environment-secrets Kubernetes Secret and is injected into the container as an environment variable. This allows any cron jobs that need to connect to the administration database to do so securely without hardcoding the connection string in the application code or configuration files.
        - name: EventMessageQueueSettings__Host
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: event-bus-host
        - name: EventMessageQueueSettings__UserName
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: event-bus-user-name
        - name: EventMessageQueueSettings__Password
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: event-bus-password
        volumeMounts: ## We define the volume mounts for the container, which includes the PersistentVolumeClaim for the administration service. This tells Kubernetes to mount the persistent volume to the specified path in the container, ensuring that data such as data protection keys is stored persistently and can be shared with any related cron jobs.
        - name:  administration-service-pvc ## The name of the PersistentVolumeClaim defined above
          mountPath:  /root/.aspnet/DataProtection-Keys
      volumes: ## We define the volumes for the Deployment, which includes the PersistentVolumeClaim for the administration service. This tells Kubernetes to create a volume based on the PVC and mount it to the specified path in the container, ensuring that data such as data protection keys is stored persistently and can be shared with any related cron jobs.
        - name:  administration-service-pvc ## The name of the PersistentVolumeClaim defined above
          persistentVolumeClaim:
            claimName: administration-service-pvc ## The name of the PersistentVolumeClaim defined above. This tells Kubernetes to use the existing PVC for the Deployment, ensuring that the data stored in the /root/.aspnet/DataProtection-Keys directory is persisted across pod restarts and can be shared with any cron jobs that also mount this PVC.
